---
title: "networkcomparision"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

make_table <- #Transform .csv file to two by tow tables
  function(a,b,c,d,row1,row2,col1,col2)
    
  {
    
    .Table <- matrix(c(a, b, c, d), 2, 2, byrow=T, dimnames=list(c(row1, row2), c(col1, col2)))
    return(.Table)
  }



mantelhaen_esimate <- 
  function(tablelist,num_level)
  {
    
    library("lawstat")
    Stra <- array(tablelist,dim=c(2,2,num_level)) # Creat a 2*2*n array, n is the dimber of stratify
    results <- mantelhaen.test(Stra) # Cochran-Mantel-Haenszel chi-squared test of the null that two nominal variables are conditionally independent in each stratum
    
    
    OR <- round(as.numeric(results$estimate),2) # Point estimate of OR
    down <- round(as.numeric(results$conf.int)[1],2) #lower bounds of CI
    up <- round(as.numeric(results$conf.int)[2],2) # upper counds of CI
    stat <- results$statistic # Chi-sq statistics 
    p_val <- results$p.value # P-value
    Interval <- paste(OR," (",down,"-",up,")",sep = "") #CI
    
    OR_CI <- data.frame(AOR = OR,CI = Interval,down = down,up = up,p_val = p_val)
    
    return(OR_CI)
    
  }



CMH <- ## perform CMH test for each file
  function(path,file)
  {
    
    row1 <- "Drug";  row2 <- "No Drug";  col1 <- "Dementia"; col2 <- "No Dementia"
  
    Sti_drug <- read.csv(paste(path,file,sep = ""))
    num_level <- dim(Sti_drug)[1] # Number of stratify
    table_list <- c()
  
    for (i in 1:num_level){
      group_row <- Sti_drug[i,]
      
      ### Note: Use the same row names as in CSV file
      a <- as.numeric(group_row$Dementia_drug)
      b <- as.numeric(group_row$Other_drug)
      c <- as.numeric(group_row$Dementia_control)
      d <- as.numeric(group_row$Other_control)
      
      group_table <- make_table(a,b,c,d,row1,row2,col1,col2)
      
      table_list <- c(table_list,group_table)
    }

      AOR_CI <- mantelhaen_esimate(table_list,num_level)
      
      return(AOR_CI)
  }


path <- "/Users/yihengpan/Desktop/AOR/" #change path
pathOut <- "/Users/yihengpan/Desktop/AOR/file/" # change path
file_list <- list.files(path,pattern = "*.csv")
AOR_CI_all <- data.frame(OR=as.numeric(),CI=as.character() ,down=as.numeric(),up=as.numeric(),P=as.numeric(),name=as.character())

require(stringr)
for (file in file_list){
  name_temp <- str_extract(file, ".*[^.csv]")
  AOR_temp <- CMH(path,file) #perform CMH test
  AOR_temp$name <- name_temp # add name of the group
  AOR_CI_all <- rbind(AOR_CI_all,AOR_temp) #add row to the existing file
}

write.csv(AOR_CI_all,paste(pathOut,"CI_out.csv",sep = ""),row.names = F,quote = F)



```



```{r}
library(forestplot)

###### Creat input database for plotlibrary(forestplot)

workdir <- "/Users/yihengpan/Desktop/AOR/plot"
datafile <- file.path(workdir,"8months-HR.csv")
Enbrel <- read.csv(datafile, stringsAsFactors=FALSE)

###### Creat input database for plot
tabletext <- cbind(c("Exposure",Enbrel$name),
                   c("Time window",Enbrel$Compare),
                   c("    HR(95% CI)",Enbrel$CI),
                   c("P-value",Enbrel$p_val),
                   c("Risk in exposure",Enbrel$risk1),
                   c("Risk in control",Enbrel$risk2),
                   c(" ", " ", " ", " ")
                   )


##### Name the figure
png(file.path(workdir,"8months-HR.png"),width=5000, height=1500)
#### plot using the input database
forestplot(labeltext=tabletext,
            align = c("c", "c", "c"),
          
           graph.pos=7, ### Number of columns on the right side of the forest plot
           ### Input confidence intervals
           mean=c(NA,Enbrel$AOR), 
           lower=c(NA,Enbrel$down), upper=c(NA,Enbrel$up),
           #xlog = TRUE,
           xlab = "HR",
           #title=expression(paste("Associations between Tumor Necrosis Factor-",alpha," Blocking Agents and Dementia (or Alzheimer's disease)",sep="")),
           xticks =  seq(0.0,2.0,0.5), ###range of x axis
           lwd.xaxis = 18, ### width of x axis
           #lwd.zero = 0,  ### width of zero line
           #xlab="<--Use drug Better    Adjusted Odds Ratio    No drug Better-->", ##name of x axis
           hrzl_lines=list("2" = gpar(lwd=8, col="black",columns=1:6)),
           ######## font sizes
           txt_gp=fpTxtGp(label=gpar(cex=8),
                          ticks=gpar(cex=6),
                          xlab=gpar(cex=6),
                          title=gpar(cex=6)),
           #gp = gpar(fill = "black", col="black"),
           grid = structure(c(1.0), gp = gpar(col = "black", lty=3,lwd = 10)),
           ###### plot color
           col=fpColors(box="black",lines="black", zero = "white"),
           ###### adjust the plot of confidence intervals
           cex=2.5, lineheight = unit(8,'cm'), colgap=unit(6,"mm"),
           lwd.ci=15, ci.vertices=TRUE,ci.vertices.height = 0.20,boxsize = 0.1

                      
           )

dev.off()



```



```{r}
library(forestplot)

###### Creat input database for plotlibrary(forestplot)

workdir <- "/Users/yihengpan/Desktop/AOR/plot"
datafile <- file.path(workdir,"SSRI-SAIR-7.csv")
Enbrel <- read.csv(datafile, stringsAsFactors=FALSE)

###### Creat input database for plot
tabletext <- cbind(c("Control",Enbrel$name),
                   c("Outcome",Enbrel$Compare),
                   c("    HR(95% CI)",Enbrel$CI),
                   c("P-value",Enbrel$p_val),
                   c(" ", " ", " ", " ")
                   )


##### Name the figure
png(file.path(workdir,"covid-sair-7.png"),width=5000, height=1500)
#### plot using the input database
forestplot(labeltext=tabletext,
            align = c("l", "l", "l"),
          
           graph.pos=5, ### Number of columns on the right side of the forest plot
           ### Input confidence intervals
           mean=c(NA,Enbrel$AOR), 
           lower=c(NA,Enbrel$down), upper=c(NA,Enbrel$up),
           #xlog = TRUE,
           xlab = "HR",
           #title=expression(paste("Associations between Tumor Necrosis Factor-",alpha," Blocking Agents and Dementia (or Alzheimer's disease)",sep="")),
           xticks = seq(0.0,25.0,5), ###range of x axis
           lwd.xaxis = 18, ### width of x axis
           #lwd.zero = 0,  ### width of zero line
           #xlab="<--Use drug Better    Adjusted Odds Ratio    No drug Better-->", ##name of x axis
           hrzl_lines=list("2" = gpar(lwd=8, col="black",columns=1:4)),
           ######## font sizes
           txt_gp=fpTxtGp(label=gpar(cex=8),
                          ticks=gpar(cex=6),
                          xlab=gpar(cex=6),
                          title=gpar(cex=6)),
           #gp = gpar(fill = "black", col="black"),
           grid = structure(c(1.0), gp = gpar(col = "black", lty=3,lwd = 10)),
           ###### plot color
           col=fpColors(box="black",lines="black", zero = "white"),
           ###### adjust the plot of confidence intervals
           cex=2.5, lineheight = unit(12,'cm'), colgap=unit(6,"mm"),
           lwd.ci=15, ci.vertices=TRUE,ci.vertices.height = 0.20,boxsize = 0.1)

dev.off()



```



```{r}
library(CALIBERdatamanage)
png(file.path(workdir,"covid-sair-7.png"),width=1000, height=500)
data(test_multiforest)
multiforest(test_multiforest)
multiforestPNG(test_multiforest)
dev.off()
```


